// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHQrQF_l_nI45u4ibFXtq81XyhzpYjA4w',
    appId: '1:598905427740:web:30d5ae5d77a45a777f8cd9',
    messagingSenderId: '598905427740',
    projectId: 'adoptanddonate-6e5f8',
    authDomain: 'adoptanddonate-6e5f8.firebaseapp.com',
    storageBucket: 'adoptanddonate-6e5f8.firebasestorage.app',
    measurementId: 'G-695X5EC6XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj55xcuMgZIpjbaeHfjzAFKn-M_oqS84w',
    appId: '1:598905427740:android:0d974e2c94f828db7f8cd9',
    messagingSenderId: '598905427740',
    projectId: 'adoptanddonate-6e5f8',
    storageBucket: 'adoptanddonate-6e5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzdh7gChhFXtu8VaUWs9n1f0eqEsRBOE',
    appId: '1:598905427740:ios:2c0576ad75dc94237f8cd9',
    messagingSenderId: '598905427740',
    projectId: 'adoptanddonate-6e5f8',
    storageBucket: 'adoptanddonate-6e5f8.firebasestorage.app',
    iosBundleId: 'com.example.adoptanddonate_new',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzdh7gChhFXtu8VaUWs9n1f0eqEsRBOE',
    appId: '1:598905427740:ios:2c0576ad75dc94237f8cd9',
    messagingSenderId: '598905427740',
    projectId: 'adoptanddonate-6e5f8',
    storageBucket: 'adoptanddonate-6e5f8.firebasestorage.app',
    iosBundleId: 'com.example.adoptanddonate_new',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHQrQF_l_nI45u4ibFXtq81XyhzpYjA4w',
    appId: '1:598905427740:web:719f06565d53de677f8cd9',
    messagingSenderId: '598905427740',
    projectId: 'adoptanddonate-6e5f8',
    authDomain: 'adoptanddonate-6e5f8.firebaseapp.com',
    storageBucket: 'adoptanddonate-6e5f8.firebasestorage.app',
    measurementId: 'G-4T7W940G8N',
  );
}
